version: '3'

services:
  web:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile.prod
    command: gunicorn Crown.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/BackEnd/web/static
      - media_volume:/home/BackEnd/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on: 
      - db
  db: 
    image: postgres:alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/BackEnd/web/static
      - media_volume:/home/BackEnd/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: