# Generated by Django 2.2.3 on 2019-09-17 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('convocatoria', models.ImageField(blank=True, null=True, upload_to='licitaciones/convocatorias')),
                ('ciudad', models.CharField(choices=[('LAPAZ', 'La Paz'), ('SANTACRUZ', 'Santa Cruz'), ('COCHABAMBA', 'Cochabamba'), ('ORURO', 'Oruro'), ('POTOSI', 'Potosi'), ('TARIJA', 'Tarija'), ('SUCRE', 'Sucre'), ('BENI', 'Beni'), ('PANDO', 'Pando')], max_length=20)),
                ('item', models.CharField(choices=[('CAMIONETA', 'Camioneta'), ('VAGONETA', 'Vagoneta'), ('AMBULANCIA', 'Ambulancia'), ('EXCAVADORA', 'Excavadora'), ('RETROEXCAVADORA', 'Retroexcavadora'), ('CARROBOMBERO', 'Carro Bombero'), ('CARROBASURERO', 'Carro Basurero'), ('MOTO', 'Moto')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('marca', models.CharField(choices=[('INDEFINIDO', 'Por Definir'), ('TOYOTA', 'Toyota'), ('HINO', 'Hino'), ('VOLVO', 'Volvo'), ('SINOTRUK', 'Sinotruk'), ('YAMAHA', 'Yamaha'), ('MAXUS', 'Maxus')], max_length=20)),
                ('monto_ref', models.IntegerField()),
                ('estado', models.CharField(choices=[('INDEFINIDO', 'Por Definir'), ('EVALUACION', 'En Evaluacion'), ('REUNION', 'Proxima Reunion'), ('PARTICIPACION', 'Se Participara')], max_length=20)),
                ('presentacion', models.DateField(default='2019-01-01')),
                ('observacion', models.TextField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
