# Generated by Django 2.2.3 on 2019-10-14 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.DateField(default='2019-01-01')),
                ('observacion', models.TextField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.Licitacion')),
            ],
        ),
    ]
