# Generated by Django 2.2.3 on 2019-08-31 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('empresa', models.CharField(choices=[('CROWN', 'Crown'), ('TOYOSA', 'Toyosa'), ('TOYOTA', 'Toyota')], max_length=30)),
                ('codigo', models.CharField(help_text='El codigo de la agencia debe contener 6 digitos Ejemplo: LPZ001', max_length=6, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='users/agencias')),
                ('pais', models.CharField(choices=[('BOLIVIA', 'Bolivia'), ('CHILE', 'Chile'), ('CUBA', 'Cuba'), ('EEUU', 'Estados Unidos')], max_length=30)),
                ('ciudad', models.CharField(choices=[('LAPAZ', 'La Paz'), ('SANTACRUZ', 'Santa Cruz'), ('COCHABAMBA', 'Cochabamba'), ('ORURO', 'Oruro'), ('POTOSI', 'Potosi'), ('TARIJA', 'Tarija'), ('SUCRE', 'Sucre'), ('BENI', 'Beni'), ('PANDO', 'Pando')], max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('lat', models.CharField(blank=True, max_length=50)),
                ('lng', models.CharField(blank=True, max_length=50)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('telefono2', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=30)),
                ('nacimiento', models.DateField(default='1985-01-01')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/fotosperfil')),
                ('segundo_nombre', models.CharField(blank=True, max_length=20)),
                ('segundo_apellido', models.CharField(blank=True, max_length=20)),
                ('documento', models.CharField(choices=[('CI', 'Cedula de Identidad'), ('PE', 'Carnet de Extranjero'), ('PAS', 'Pasaporte'), ('CD', 'Cedula de Identidad Duplicada')], default='CI', max_length=30)),
                ('ci', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ciextend', models.CharField(blank=True, max_length=10)),
                ('expedido', models.CharField(choices=[('LPZ', 'La Paz'), ('SCZ', 'Santa Cruz'), ('CBA', 'Cochabamba'), ('TJA', 'Tarija'), ('CHQ', 'Chuquisaca'), ('ORU', 'Oruro'), ('PSI', 'Potosi'), ('BNI', 'Beni'), ('PND', 'Pando')], max_length=20)),
                ('ciudad', models.CharField(choices=[('LPZ', 'La Paz'), ('SCZ', 'Santa Cruz'), ('CBA', 'Cochabamba'), ('TJA', 'Tarija'), ('CHQ', 'Chuquisaca'), ('ORU', 'Oruro'), ('PSI', 'Potosi'), ('BNI', 'Beni'), ('PND', 'Pando')], max_length=20)),
                ('direccion', models.CharField(max_length=300)),
                ('lat', models.CharField(blank=True, max_length=50)),
                ('lng', models.CharField(blank=True, max_length=50)),
                ('cel_corp', models.IntegerField(blank=True, null=True)),
                ('tel_corp', models.IntegerField(blank=True, null=True)),
                ('interno', models.IntegerField(blank=True, null=True)),
                ('cel_per', models.IntegerField(blank=True, null=True)),
                ('tel_per', models.IntegerField(blank=True, null=True)),
                ('nom_emer', models.CharField(blank=True, max_length=10)),
                ('tel_emer', models.IntegerField(blank=True, null=True)),
                ('cargo', models.CharField(choices=[('GERENTE', 'Gerente'), ('SUBGERENTE', 'Sub Gerente'), ('JEFE', 'Jefe'), ('RESPONSABLE', 'Responsable'), ('ANALISTA', 'Analista'), ('EJECUTIVO', 'Ejecutivo'), ('ASISTENTE', 'Asistente'), ('MECANICO', 'Mecanico'), ('MENSAJERO', 'Mensajero'), ('PASANTE', 'Pasante')], max_length=30)),
                ('area', models.CharField(choices=[('VENTAS', 'Ventas'), ('FINANZAS', 'Finanzas'), ('CARTERA', 'Cartera'), ('MARKETING', 'Marketing'), ('CONTABILIDAD', 'Contabilidad'), ('RRHH', 'Recursos Humanos'), ('SISTEMAS', 'Sistemas'), ('SERVICIOS', 'Servicios'), ('TALLER', 'Taller'), ('LICITACIONES', 'Licitaciones'), ('IMPORTACIONES', 'Importaciones'), ('LEGAL', 'Legal'), ('AGENCIAINTERNA', 'Agencia Interna')], max_length=30)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Baja'), ('BAJATEMP', 'Baja Temporal')], max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Agencia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
